### PR TITLE
Add CocoaPod installation notes to the readme

### PR DESCRIPTION
**Pull request by chris-garrett**
Add CocoaPod installation notes to the readme.

### CODE REVIEW

**Comment by tomburns** [comment]
This shouldn't be necessary; it looks like the podfile was not submitted to the main Cocoapods repository. I'll get a pull request in to fix that.

**Comment by tomburns** [comment]
No longer necessary, see comments on #13.

**Comment by chris-garrett** [comment]
I'll modify the readme when I get home to reflect the change.

**Comment by tomburns** [comment]
Closing now that the pod is in the main Specs repo.

**Pull request closed without merging**
