### PR TITLE
Create Podspec file and add basic info

### PR DESCRIPTION
**Pull request by tomburns**
Needs a version tag in the repo to be ready for release, and a once-over depending on your personal preferences.

Once you've tagged a release, you can 

`$ pod spec lint TWTSideMenuViewController.podspec`

to vet it and make sure things are configured properly.

### CODE REVIEW

**Comment by jnjosh** [comment]
Wow, thanks for adding this! Would you mind cleaning up all the boiler plate stuff from the podspec? It really only needs to have the things that aren't commented out. Also, I added a tag: v0.1.

**Comment by tomburns** [comment]
Done. New commit on this branch now has a podspec that passes validation for v0.1!

```
tburns@orpheus ~/code/TWTSideMenuViewController [create-podspec]
± % pod spec lint TWTSideMenuViewController.podspec                                                             !4267

 -> TWTSideMenuViewController (0.1)

Analyzed 1 podspec.

TWTSideMenuViewController.podspec passed validation.
```

**Comment by tomburns** [comment]
Ping - let me know if this needs anything else for a merge!

**Comment by fyell** [comment]
@tomburns Perfect timing. Was just about to check if there was a podspec for this :+1:

**Comment by jnjosh** [comment]
Yep, I'll work on getting it added to the CocoaPods repo tonight.

**Pull request merged**
